### ISSUE TITLE
Selenium and morph.io

### ISSUE THREAD

**Issue by markbrough** [andylolz/country-codes#1]
This scraper appears to have stopped working on morph.io -- it looks like the issue is possibly this:
https://help.morph.io/t/chromedriver-broken-in-scraper/566/3

Here is an example of a python scraper that is working and uses selenium:
https://morph.io/Kooben209/PP-RM-LON

Perhaps just adding the platform file as he mentions might work?
https://github.com/Kooben209/PP-RM-LON/blob/master/platform

**Comment by andylolz** [comment]
> Perhaps just adding the platform file as he mentions might work?

Yes! You’re right. That seems to have fixed it!
